include ./kitty_gruvbox_theme/gruvbox_dark_hard.conf
#fonts

font_family Iosevka
italic_font Iosevka # Ensures non-italicized font is used for italics
font_features +calt,-ital  # Adjust features if thin italics appear
bold_font Iosevka
font_weight medium

#keybinds. Wezterm equivalent
map ctrl+= zoom_in
map ctrl+- zoom_out
map ctrl+0 zoom_reset

background_opacity 0.9


font_size 18.0
